version: "3.7"

services:
  nextjs-tailwind:
    build: ../nextjs-tailwind-starter
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextjs-tailwind.rule=Host(`nextjs-tailwind.${DOMAIN_NAME}`)"
      - "traefik.http.routers.nextjs-tailwind.entryPoints=http"
      - "traefik.http.routers.nextjs-tailwind.middlewares=https_redirect"
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.nextjs-tailwind_tls.rule=Host(`nextjs-tailwind.${DOMAIN_NAME}`)"
      - "traefik.http.routers.nextjs-tailwind_tls.entryPoints=https"
      - "traefik.http.routers.nextjs-tailwind_tls.tls.certresolver=mydnschallenge"
